insert into stoic_quotes (body, author, source_work) values
('When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love.', 'Marcus Aurelius', 'Meditations'),
('You have power over your mind - not outside events. Realize this, and you will find strength.', 'Marcus Aurelius', 'Meditations'),
('The happiness of your life depends upon the quality of your thoughts.', 'Marcus Aurelius', 'Meditations'),
('Waste no more time arguing about what a good man should be. Be one.', 'Marcus Aurelius', 'Meditations'),
('The best revenge is to be unlike him who performed the injury.', 'Marcus Aurelius', 'Meditations'),
('Very little is needed to make a happy life; it is all within yourself, in your way of thinking.', 'Marcus Aurelius', 'Meditations'),
('If it is not right do not do it; if it is not true do not say it.', 'Marcus Aurelius', 'Meditations'),
('Confine yourself to the present.', 'Marcus Aurelius', 'Meditations'),
('Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.', 'Marcus Aurelius', 'Meditations'),
('How much trouble he avoids who does not look to see what his neighbour says or does or thinks.', 'Marcus Aurelius', 'Meditations'),
('Loss is nothing else but change, and change is Nature''s delight.', 'Marcus Aurelius', 'Meditations'),
('Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart.', 'Marcus Aurelius', 'Meditations'),
('Death smiles at us all; all we can do is smile back.', 'Marcus Aurelius', 'Meditations'),
('Our life is what our thoughts make it.', 'Marcus Aurelius', 'Meditations'),
('Be tolerant with others and strict with yourself.', 'Marcus Aurelius', 'Meditations'),
('The soul becomes dyed with the colour of its thoughts.', 'Marcus Aurelius', 'Meditations'),
('Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.', 'Marcus Aurelius', 'Meditations'),
('Dwell on the beauty of life. Watch the stars, and see yourself running with them.', 'Marcus Aurelius', 'Meditations'),
('It is not death that a man should fear, but he should fear never beginning to live.', 'Marcus Aurelius', 'Meditations'),
('The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.', 'Marcus Aurelius', 'Meditations'),
('Reject your sense of injury and the injury itself disappears.', 'Marcus Aurelius', 'Meditations'),
('A man''s worth is no greater than the worth of his ambitions.', 'Marcus Aurelius', 'Meditations'),
('Do every act of your life as if it were the last.', 'Marcus Aurelius', 'Meditations'),
('Nowhere can man find a quieter or more untroubled retreat than in his own soul.', 'Marcus Aurelius', 'Meditations'),
('Adapt yourself to the things among which your lot has been cast and love sincerely the fellow creatures with whom destiny has ordained that you shall live.', 'Marcus Aurelius', 'Meditations'),
('The universe is change; our life is what our thoughts make it.', 'Marcus Aurelius', 'Meditations'),
('To live happily is an inward power of the soul.', 'Marcus Aurelius', 'Meditations'),
('That which is not good for the swarm is not good for the bee.', 'Marcus Aurelius', 'Meditations'),
('Begin each day by telling yourself: today I shall be meeting with interference, ingratitude, insolence, disloyalty, ill-will, and selfishness.', 'Marcus Aurelius', 'Meditations'),
('How much more grievous are the consequences of anger than the causes of it.', 'Marcus Aurelius', 'Meditations'),
('When you wake up in the morning, tell yourself: the people I deal with today will be meddling, ungrateful, arrogant. Yet none can implicate me in ugliness.', 'Marcus Aurelius', 'Meditations'),
('Receive without conceit, release without struggle.', 'Marcus Aurelius', 'Meditations'),
('Concentrate every minute on doing what''s in front of you with precise and genuine seriousness, tenderly, willingly, with justice.', 'Marcus Aurelius', 'Meditations'),
('The art of living is more like wrestling than dancing.', 'Marcus Aurelius', 'Meditations'),
('Choose not to be harmed and you won''t feel harmed. Don''t feel harmed and you haven''t been.', 'Marcus Aurelius', 'Meditations'),
('If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke.', 'Marcus Aurelius', 'Meditations'),
('No man is free who is not master of himself.', 'Epictetus', 'Discourses'),
('It''s not what happens to you, but how you react to it that matters.', 'Epictetus', 'Enchiridion'),
('Men are disturbed not by the things which happen, but by the opinions about the things.', 'Epictetus', 'Enchiridion'),
('Make the best use of what is in your power, and take the rest as it happens.', 'Epictetus', 'Discourses'),
('We have two ears and one mouth so that we can listen twice as much as we speak.', 'Epictetus', 'Discourses'),
('Wealth consists not in having great possessions, but in having few wants.', 'Epictetus', 'Discourses'),
('First say to yourself what you would be; and then do what you have to do.', 'Epictetus', 'Discourses'),
('He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.', 'Epictetus', 'Discourses'),
('Don''t explain your philosophy. Embody it.', 'Epictetus', 'Discourses'),
('Only the educated are free.', 'Epictetus', 'Discourses'),
('If you want to improve, be content to be thought foolish and stupid.', 'Epictetus', 'Enchiridion'),
('No man is free who is not master of himself, and yet does not control the things he cannot.', 'Epictetus', 'Discourses'),
('Seek not that the things which happen should happen as you wish; but wish the things which happen to be as they are, and you will have a tranquil flow of life.', 'Epictetus', 'Enchiridion'),
('It is impossible for a man to learn what he thinks he already knows.', 'Epictetus', 'Discourses'),
('Any person capable of angering you becomes your master.', 'Epictetus', 'Discourses'),
('There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will.', 'Epictetus', 'Discourses'),
('Difficulties are things that show a person what they are.', 'Epictetus', 'Discourses'),
('Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.', 'Epictetus', 'Discourses'),
('Circumstances don''t make the man, they only reveal him to himself.', 'Epictetus', 'Discourses'),
('Know, first, who you are, and then adorn yourself accordingly.', 'Epictetus', 'Discourses'),
('Caretake this moment. Immerse yourself in its particulars. Respond to this person, this challenge, this deed.', 'Epictetus', 'Discourses'),
('Practice yourself, for heaven''s sake, in little things; and thence proceed to greater.', 'Epictetus', 'Discourses'),
('The greater the difficulty, the more glory in surmounting it.', 'Epictetus', 'Discourses'),
('Don''t just say you have read books. Show that through them you have learned to think better.', 'Epictetus', 'Discourses'),
('What concerns me is not the way things are, but rather the way people think things are.', 'Epictetus', 'Discourses'),
('Attach yourself to what is spiritually superior, regardless of what other people think or do.', 'Epictetus', 'Discourses'),
('To accuse others for one''s own misfortunes is a sign of want of education.', 'Epictetus', 'Enchiridion'),
('Demand not that events should happen as you wish; but wish them to happen as they do, and you will go on well.', 'Epictetus', 'Enchiridion'),
('Remember that you are an actor in a play, which is as the playwright wants it to be.', 'Epictetus', 'Enchiridion'),
('Sickness is an impediment to the body, but not to the will, unless the will itself chooses.', 'Epictetus', 'Enchiridion'),
('When you are going about any action, remind yourself what nature the action is.', 'Epictetus', 'Enchiridion'),
('Now is the time to get serious about living your ideals. Once you have determined the spiritual things you want, do not put off acting on them.', 'Epictetus', 'Enchiridion'),
('If you wish to be a writer, write.', 'Epictetus', 'Discourses'),
('He who laughs at himself never runs out of things to laugh at.', 'Epictetus', 'Discourses'),
('Other people''s views and troubles can be contagious. Don''t sabotage yourself by unwittingly adopting negative, unproductive attitudes.', 'Epictetus', 'Discourses'),
('It is the act of an ill-instructed man to blame others for his own bad condition; it is the act of one who has begun to be instructed to lay the blame on himself.', 'Epictetus', 'Enchiridion'),
('Keep silence for the most part, and speak only when you must, and then briefly.', 'Epictetus', 'Enchiridion'),
('If anyone tells you that a certain person speaks ill of you, do not make excuses, but answer: He was ignorant of my other faults, else he would not have mentioned these alone.', 'Epictetus', 'Enchiridion'),
('We are not disturbed by what happens to us, but by our thoughts about what happens.', 'Epictetus', 'Enchiridion'),
('Nature has given to men one tongue but two ears, that we may hear from others twice as much as we speak.', 'Epictetus', 'Discourses'),
('Whoever does not regard what he has as most ample wealth, is unhappy, though he be master of the world.', 'Seneca', 'Letters from a Stoic'),
('We suffer more often in imagination than in reality.', 'Seneca', 'Letters from a Stoic'),
('Luck is what happens when preparation meets opportunity.', 'Seneca', 'Letters from a Stoic'),
('It is not that we have a short time to live, but that we waste a lot of it.', 'Seneca', 'On the Shortness of Life'),
('As is a tale, so is life: not how long it is, but how good it is, is what matters.', 'Seneca', 'Letters from a Stoic'),
('Difficulties strengthen the mind, as labour does the body.', 'Seneca', 'Letters from a Stoic'),
('Begin at once to live, and count each separate day as a separate life.', 'Seneca', 'Letters from a Stoic'),
('No man was ever wise by chance.', 'Seneca', 'Letters from a Stoic'),
('While we wait for life, life passes.', 'Seneca', 'Letters from a Stoic'),
('Sometimes even to live is an act of courage.', 'Seneca', 'Letters from a Stoic'),
('A gem cannot be polished without friction, nor a man perfected without trials.', 'Seneca', 'On Providence'),
('He suffers more than necessary, who suffers before it is necessary.', 'Seneca', 'Letters from a Stoic'),
('Every new beginning comes from some other beginning''s end.', 'Seneca', 'Letters from a Stoic'),
('If a man knows not to which port he sails, no wind is favorable.', 'Seneca', 'Letters from a Stoic'),
('The mind that is anxious about future events is miserable.', 'Seneca', 'Letters from a Stoic'),
('We are more often frightened than hurt; and we suffer more from imagination than from reality.', 'Seneca', 'Letters from a Stoic'),
('It is the power of the mind to be unconquerable.', 'Seneca', 'Letters from a Stoic'),
('As long as you live, keep learning how to live.', 'Seneca', 'Letters from a Stoic'),
('True happiness is to enjoy the present, without anxious dependence upon the future.', 'Seneca', 'On the Happy Life'),
('Most powerful is he who has himself in his own power.', 'Seneca', 'Letters from a Stoic'),
('We should every night call ourselves to an account: What infirmity have I mastered today?', 'Seneca', 'On Anger'),
('It does not matter what you bear, but how you bear it.', 'Seneca', 'On Providence'),
('A great fortune is a great slavery.', 'Seneca', 'Letters from a Stoic'),
('No person has the power to have everything they want, but it is in their power not to want what they don''t have.', 'Seneca', 'Letters from a Stoic'),
('Wherever there is a human being, there is an opportunity for a kindness.', 'Seneca', 'On the Happy Life'),
('He who is brave is free.', 'Seneca', 'Letters from a Stoic'),
('Throw me to the wolves and I will return leading the pack.', 'Seneca', 'On Providence'),
('Time discovers truth.', 'Seneca', 'Letters from a Stoic'),
('Anger, if not restrained, is frequently more hurtful to us than the injury that provokes it.', 'Seneca', 'On Anger'),
('The whole future lies in uncertainty: live immediately.', 'Seneca', 'On the Shortness of Life'),
('Life is long enough, and a sufficiently generous amount has been given to us for the highest achievements if it were all well invested.', 'Seneca', 'On the Shortness of Life'),
('They lose the day in expectation of the night, and the night in fear of the dawn.', 'Seneca', 'Letters from a Stoic'),
('You act like mortals in all that you fear, and like immortals in all that you desire.', 'Seneca', 'On the Shortness of Life'),
('Hang on to your youthful enthusiasms - you''ll be able to use them better when you''re older.', 'Seneca', 'Letters from a Stoic'),
('A well-governed appetite is the greater part of liberty.', 'Seneca', 'Letters from a Stoic'),
('It is a rough road that leads to the heights of greatness.', 'Seneca', 'Letters from a Stoic'),
('No one can have all he wants, but a man can refrain from wanting what he has not, and cheerfully make the best of a bird in the hand.', 'Seneca', 'Letters from a Stoic'),
('Associate with people who are likely to improve you.', 'Seneca', 'Letters from a Stoic'),
('Nothing is burdensome if taken lightly, and nothing need arouse one''s irritation so long as one doesn''t make it bigger than it is.', 'Seneca', 'Letters from a Stoic'),
('The greatest obstacle to living is expectancy, which hangs upon tomorrow and loses today.', 'Seneca', 'On the Shortness of Life'),
('Cling tooth and nail to the present moment, for it slips from our grasp.', 'Seneca', 'On the Shortness of Life'),
('You ask what is the proper limit to a person''s wealth? First, having what is essential, and second, having what is enough.', 'Seneca', 'Letters from a Stoic'),
('There is no enjoying the possession of anything valuable unless one has someone to share it with.', 'Seneca', 'Letters from a Stoic'),
('It is the sign of a weak mind to be unable to bear wealth.', 'Seneca', 'Letters from a Stoic'),
('How does it help to make troubles heavier by bemoaning them?', 'Seneca', 'Letters from a Stoic'),
('What need is there to weep over parts of life? The whole of it calls for tears.', 'Seneca', 'Letters from a Stoic'),
('Until we have begun to go without them, we fail to realize how unnecessary many things are.', 'Seneca', 'Letters from a Stoic'),
('I shall never be ashamed of citing a bad author if the line is good.', 'Seneca', 'Letters from a Stoic'),
('A sword never kills anybody; it is a tool in the killer''s hand.', 'Seneca', 'Letters from a Stoic'),
('No man is more unhappy than he who never faces adversity, for he is not permitted to prove himself.', 'Seneca', 'On Providence'),
('Just as the story, so is life: what matters is not how long it is, but how good it is.', 'Seneca', 'Letters from a Stoic'),
('Where fear is, happiness is not.', 'Seneca', 'Letters from a Stoic'),
('All cruelty springs from weakness.', 'Seneca', 'On Anger'),
('Things that were hard to bear are sweet to remember.', 'Seneca', 'Letters from a Stoic'),
('Treat your inferiors as you would be treated by your superiors.', 'Seneca', 'Letters from a Stoic'),
('A consciousness of wrongdoing is the first step to salvation.', 'Seneca', 'Letters from a Stoic'),
('You will hear many men saying: After my fiftieth year I shall retire into leisure; my sixtieth year shall release me from public duties.', 'Seneca', 'On the Shortness of Life'),
('Nature does not bestow virtue; to be good is an art.', 'Seneca', 'Letters from a Stoic'),
('There is nothing the wise man does reluctantly.', 'Seneca', 'On the Happy Life'),
('Look back in memory and consider the changing patterns of your moods, your numberless activities.', 'Seneca', 'On the Shortness of Life'),
('Disease is not of the body but of the place.', 'Seneca', 'Letters from a Stoic'),
('He who fears death will never do anything worthy of a living man.', 'Seneca', 'Letters from a Stoic'),
('Postponement is the greatest waste of life: it deprives us of each day as it comes, it snatches from us the present by promising the future.', 'Seneca', 'On the Shortness of Life'),
('A person''s fears are lighter when the danger is at hand.', 'Seneca', 'Letters from a Stoic'),
('To be everywhere is to be nowhere.', 'Seneca', 'Letters from a Stoic'),
('Do not consider anything for your interest which makes you break your word, quit your modesty, or inclines you to any practice which will not bear the light.', 'Marcus Aurelius', 'Meditations'),
('The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.', 'Marcus Aurelius', 'Meditations'),
('Nothing happens to any man that he is not formed by nature to bear.', 'Marcus Aurelius', 'Meditations'),
('Each day provides its own gifts.', 'Marcus Aurelius', 'Meditations'),
('Let men see, let them know, a real man, who lives as he was meant to live.', 'Marcus Aurelius', 'Meditations'),
('Think of yourself as dead. You have lived your life. Now take what''s left and live it properly.', 'Marcus Aurelius', 'Meditations'),
('Everything that exists is in a manner the seed of that which will be.', 'Marcus Aurelius', 'Meditations'),
('Anger cannot be dishonest.', 'Marcus Aurelius', 'Meditations'),
('How ridiculous and how strange to be surprised at anything which happens in life.', 'Marcus Aurelius', 'Meditations'),
('Whatever happens at all happens as it should; you will find this true, if you watch narrowly.', 'Marcus Aurelius', 'Meditations'),
('Observe constantly that all things take place by change, and accustom thyself to consider that the nature of the Universe loves nothing so much as to change.', 'Marcus Aurelius', 'Meditations'),
('Give yourself a gift: the present moment.', 'Marcus Aurelius', 'Meditations'),
('Such as are your habitual thoughts, such also will be the character of your mind; for the soul is dyed by the thoughts.', 'Marcus Aurelius', 'Meditations'),
('Men exist for the sake of one another. Teach them then or bear with them.', 'Marcus Aurelius', 'Meditations'),
('Take away the complaint, I have been harmed, and the harm is taken away.', 'Marcus Aurelius', 'Meditations'),
('Remember that no man loses other life than this which he now lives, nor lives other than this which he now loses.', 'Marcus Aurelius', 'Meditations'),
('Do not act as if you had ten thousand years to throw away.', 'Marcus Aurelius', 'Meditations'),
('That which has died falls not out of the universe.', 'Marcus Aurelius', 'Meditations'),
('A wrongdoer is often a man who has left something undone, not always one who has done something.', 'Marcus Aurelius', 'Meditations');
